### PR TITLE
prgenv-nvidia cray-mpich@8.1.30 for todi

### PR DESCRIPTION
**Pull request by simonpintarelli**

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=prgenv-nvidia:24.7

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=prgenv-nvidia:24.7

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=prgenv-nvidia:24.7

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=prgenv-nvidia:24.7

**Comment by bcumming** [comment]
Closing because we should refocus on a well-defined use case before providing this.
As it is currently named, it is confusing for users.

**Pull request closed without merging**
