### PR TITLE
add linear algebra stack (PETSc, Trilinos)

### PR DESCRIPTION
**Pull request by finkandreas**
This will add PETSc, Trilinos and a couple of other 3rdparty libraries as roots.
Kokkos is not installed explicitly since it is packaged with Trilinos and it would be confusing when there are two kokkos libraries in the stack.

The GPU version disables kokkos for PETSc, because it does not build.

### CODE REVIEW

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
Let me try to summarize what we have now:
- Two uenvs, one built for complex scalars, one for duble scalars
- Trilinos / Kokkos needed bugfixed versions, so Trilinos does not bring in its own bundled kokkos version
- naming is `linalg` and `linalg-complex`. Maybe for clarity it should be `linalg-double` and `linalg-complex`

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by finkandreas** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg-complex:24.11

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linalg:24.11

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg-complex:24.11

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linalg:24.11

**Pull request merged**
