### PR TITLE
[GH200/MC] CP2K 2024.2

### PR DESCRIPTION
**Pull request by RMeli**
Changes from `2024.1`:
* `dbcsr@2.7.0` instead of `dbcsr@2.6.0`
* `cp2k@2024.2` instead of `cp2k@2024.1`
* `+plumed` instead of `~plumed`
* `cuda_arch=90` for CP2K and DBCSR instead of `cuda_arch=80`

The `dla-future-fortran` needs to be added because it's not included in Spack `0.22.1` but it is referred in the latest version of the CP2K package.

---

Compilation tested on `todi` with the `develop` view:
```
[todi][rmeli@todi-ln001 build]$ CC=mpicc CXX=mpic++ FC=mpifort cmake \
>     -GNinja \
>     -DCP2K_ENABLE_REGTESTS=ON \
>     -DCP2K_USE_LIBXC=ON \
>     -DCP2K_USE_LIBINT2=ON \
>     -DCP2K_USE_SPGLIB=ON \
>     -DCP2K_USE_ELPA=ON \
>     -DCP2K_USE_SPLA=ON \
>     -DCP2K_USE_SIRIUS=ON \
>     -DCP2K_USE_COSMA=ON \
>     -DCP2K_USE_PLUMED=ON \
>     -DCP2K_USE_ACCEL=CUDA -DCP2K_WITH_GPU=H100 \
>     ..
```

### CODE REVIEW

**Comment by RMeli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=cp2k:2024.2

**Comment by RMeli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=cp2k:2024.2

**Review by mtaillefumier — APPROVED** [review]

**Comment by RMeli** [comment]
Added `2024.2` for multi-core too, also with the latest `dbcsr` and `+plumed`. I realised `libxsmm` was missing from the views (not a root spec), so I added it also to the `2024.1` version.

**Comment by RMeli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=cp2k:2024.2

**Comment by RMeli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=cp2k:2024.2

**Comment by RMeli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=cp2k:2024.1

**Comment by bcumming** [comment]
cscs-ci run alps;system=daint;uarch=gh200;uenv=cp2k:2024.2

**Comment by bcumming** [comment]
I have deployed as `cp2k/2024.2:v1` on todi and eiger.
Will close this once we have also built and deployed on daint.alps.

**Comment by bcumming** [comment]
cscs-ci run alps;system=daint;uarch=gh200;uenv=cp2k:2024.2

**Pull request merged**
