### PR TITLE
consolidate scripts in worflow dir

### PR DESCRIPTION
**Pull request by ninamu**
Renamed scripts dir to workflow, moved toplevel scripts to workflow dir, renamed paths to previous "scripts" dir

### CODE REVIEW

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=pregenv-gnu:24.7

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Comment by ninamu** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=prgenv-gnu:24.7

**Pull request merged**
