### PR TITLE
Eurohack

### PR DESCRIPTION
**Pull request by simonpintarelli**
prgenv-gnu + gsl for Eurohack24

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9

**Comment by simonpintarelli** [comment]
Adding `fftw+openmp` as requested by @ChristopherBignamini

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=eurohack:24.9-nvhpc

**Pull request closed without merging**
