### PR TITLE
Add rfm.yml to linaro recipe

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:23.1.2

**Comment by jgphpc** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linaro-forge:23.1.2

**Comment by bcumming** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:23.1.2

**Comment by bcumming** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:23.1.2

**Comment by jgphpc** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linaro-forge:23.1.2

**Comment by jgphpc** [comment]
> cscs-ci run alps;system=eiger;uarch=zen2;uenv=linaro-forge:23.1.2

the mount point '/user-tools' must exist

**Pull request closed without merging**
