### PR TITLE
CP2K 2024.3 and F7T runner for Todi

### PR DESCRIPTION
**Pull request by RMeli**
Users hit a bug in CP2K affecting MD and cell relaxation, that has been fixed in 2024.3.

https://github.com/cp2k/cp2k/pull/3661

### CODE REVIEW

**Comment by RMeli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=cp2k:2024.3

**Comment by RMeli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=cp2k:2024.3

**Comment by RMeli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=cp2k:2024.3

**Comment by RMeli** [comment]
cscs-ci run alps;system=daint;uarch=gh200;uenv=cp2k:2024.3

**Review by bcumming — APPROVED** [review]

**Pull request merged**
