### PR TITLE
VASP: Add v6.4.3 for GH200

### PR DESCRIPTION
**Pull request by AdhocMan**
We had requests for VASP 6.4.3. This PR adds initial support for this new version with NVHPC 24.5 and CUDA 12.4.
This version of VASP adds support for cuSOLVERMp, but linking with nvhpc returns an error, indicating that it is only supported on x86. 
~~The build has not been tested with the VASP testsuite yet.~~

### CODE REVIEW

**Comment by AdhocMan** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=vasp:v6.4.2

**Comment by AdhocMan** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=vasp:v6.4.3

**Comment by AdhocMan** [comment]
The testsuite passed for this build.

Side note: I triggered building of the old version by mistake and this probably failed due to incompatibility with the latest stackinator changes.

**Comment by AdhocMan** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=vasp:v6.4.3

**Comment by bcumming** [comment]
cscs-ci run alps;system=daint;uarch=gh200;uenv=vasp:v6.4.3

**Comment by bcumming** [comment]
We had requests for VASP 6.4.3. This PR adds initial support for this new version with NVHPC 24.5 and CUDA 12.4.
This version of VASP adds support for cuSOLVERMp, but linking with nvhpc returns an error, indicating that it is only supported on x86.

**Comment by bcumming** [comment]
We had requests for VASP 6.4.3. This PR adds initial support for this new version with NVHPC 24.5 and CUDA 12.4.
This version of VASP adds support for cuSOLVERMp, but linking with nvhpc returns an error, indicating that it is only supported on x86.

**Pull request merged**
