### PR TITLE
deploy QE on todi

### PR DESCRIPTION
**Pull request by simonpintarelli**

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso

**Comment by RMeli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
@bcumming I think it is ready to merge now.

**Pull request merged**
