### PR TITLE
QE update

### PR DESCRIPTION
**Pull request by simonpintarelli**
Update QE recipe, reframe.yaml for eiger and todi.

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by RMeli** [comment]
@simonpintarelli maybe it is worth to already squeeze in the `reframe.yaml` file for QE in this PR?

**Comment by simonpintarelli** [comment]
@RMeli will add it later to this PR, first I'd like to get a working develop view, previously I tested the build only for modules.

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=quantumespresso:v7.3.1

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=quantumespresso:v7.3.1

**Pull request merged**
