### PR TITLE
Add Julia[up] UENV

### PR DESCRIPTION
**Pull request by omlins**

### CODE REVIEW

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by omlins** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=julia:24.9

**Comment by simonpintarelli** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=julia:24.9

**Pull request merged**
