### PR TITLE
linaro-forge/24

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:2024

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:24.0

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:24.0

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:24.0

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:24.0

**Comment by jgphpc** [comment]
cscs-ci run alps;system=santis;uarch=gh200;uenv=linaro-forge:24.0

**Comment by bcumming** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linaro-forge:24.0

**Comment by jgphpc** [comment]
cscs-ci run alps;system=todi;uarch=gh200;uenv=linaro-forge:24.0.2

**Comment by bcumming** [comment]
cscs-ci run alps;system=eiger;uarch=zen2;uenv=linaro-forge:24.0.2

**Comment by bcumming** [comment]
cscs-ci run alps;system=daint;uarch=zen2;uenv=linaro-forge:24.0.2

**Comment by bcumming** [comment]
cscs-ci run alps;system=daint;uarch=gh200;uenv=linaro-forge:24.0.2

**Pull request merged**
